2015-02-06 15:11:37+0530 [-] Log opened.
2015-02-06 15:11:37+0530 [-] twistd 13.2.0 (/usr/bin/python 2.7.6) starting up.
2015-02-06 15:11:37+0530 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2015-02-06 15:11:37+0530 [-] FastAGIFactory starting on 4570
2015-02-06 15:11:37+0530 [-] Starting factory <starpy.fastagi.FastAGIFactory instance at 0x7f1ea90a83f8>
2015-02-06 15:12:08+0530 [FastAGIProtocol,0,127.0.0.1] Friday
2015-02-06 15:12:08+0530 [FastAGIProtocol,0,127.0.0.1] 15:12:08
2015-02-06 15:12:08+0530 [FastAGIProtocol,0,127.0.0.1] adbapi connecting: MySQLdb {'passwd': 'deep2810', 'db': 'lectures', 'host': '127.0.0.1', 'user': 'root', 'cursorclass': <class 'MySQLdb.cursors.DictCursor'>}
2015-02-06 15:12:08+0530 [-] Unhandled error in Deferred:
2015-02-06 15:12:08+0530 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
	    self.__bootstrap_inner()
	  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
	    self.run()
	  File "/usr/lib/python2.7/threading.py", line 763, in run
	    self.__target(*self.__args, **self.__kwargs)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 191, in _worker
	    result = context.call(ctx, function, *args, **kwargs)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 448, in _runInteraction
	    result = interaction(trans, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/enterprise/adbapi.py", line 462, in _runQuery
	    trans.execute(*args, **kw)
	  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 159, in execute
	    query = query % db.literal(args)
	exceptions.TypeError: not enough arguments for format string
	
